apiVersion: apps/v1
kind: Deployment
metadata:
  name: retro-summarizer
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retro-summarizer
  template:
    metadata:
      labels:
        app: retro-summarizer
    spec:
      containers:
        - name: my-app
          image: registry.digitalocean.com/pet-projects-nastyakul/streamlit_tutorial:latest
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: summarizer-secrets
                  key: openai
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: summarizer-secrets
                  key: gcloud
          ports:
            - containerPort: 8501
          imagePullPolicy: Always
      volumes:
        - name: summarizer-secrets-volume
          secret:
            secretName: summarizer-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: retro-summarizer
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: retro-summarizer
  ports:
    - name: http
      port: 8501
      targetPort: 8501
